#ifndef __APP_CONFIG_H__
#define __APP_CONFIG_H__

#define APP_MODULE_COUNT                6U
#define APP_CELLS_PER_MODULE            23U
#define APP_TEMPS_PER_MODULE            8U
#define APP_TOTAL_CELL_COUNT            (APP_MODULE_COUNT * APP_CELLS_PER_MODULE)
#define APP_TOTAL_TEMP_COUNT            (APP_MODULE_COUNT * APP_TEMPS_PER_MODULE)
#define APP_CAN1_VOLTAGE_FRAMES_PER_MODULE  6U
#define APP_MODULE_VOLTAGE_VALID_MASK       ((uint8_t)((1U << APP_CAN1_VOLTAGE_FRAMES_PER_MODULE) - 1U))

#define APP_MOTOR_COUNT 4U

#define APP_SNAPSHOT_TIMEOUT_MS 2000U

#define APP_MODE_CMD_STRAIGHT   48U
#define APP_MODE_CMD_AUTOCROSS  49U
#define APP_MODE_CMD_SKIDPAD    50U
#define APP_MODE_CMD_ENDURANCE  51U

#define APP_COMMAND_RX_BUFFER_SIZE 16U
#define APP_COMMAND_RX_IDLE_MS     20U

#endif /* __APP_CONFIG_H__ */
