#ifndef __APP_CONFIG_H__
#define __APP_CONFIG_H__

#define APP_MODULE_COUNT                6U
#define APP_CELLS_PER_MODULE            23U
#define APP_TEMPS_PER_MODULE            8U
#define APP_TOTAL_CELL_COUNT            (APP_MODULE_COUNT * APP_CELLS_PER_MODULE)
#define APP_TOTAL_TEMP_COUNT            (APP_MODULE_COUNT * APP_TEMPS_PER_MODULE)
#define APP_CAN1_VOLTAGE_FRAMES_PER_MODULE  6U
#define APP_MODULE_VOLTAGE_VALID_MASK       ((uint8_t)((1U << APP_CAN1_VOLTAGE_FRAMES_PER_MODULE) - 1U))

#define APP_MOTOR_COUNT 4U

#define APP_SNAPSHOT_TIMEOUT_MS 2000U

#define APP_MODE_CMD_STRAIGHT   48U
#define APP_MODE_CMD_AUTOCROSS  49U
#define APP_MODE_CMD_SKIDPAD    50U
#define APP_MODE_CMD_ENDURANCE  51U

#define APP_COMMAND_RX_BUFFER_SIZE 16U
#define APP_COMMAND_RX_IDLE_MS     20U

#define APP_CAN1_PACK_SUMMARY_ID        0x186050F4UL
#define APP_CAN2_MODE_COMMAND_ID        0x0310U

#define APP_IVT_RESULT_ERROR_MASK       0x0EU
#define APP_ENERGY_METER_SOURCE_UNKNOWN 0U
#define APP_ENERGY_METER_SOURCE_IVT     1U
#define APP_ENERGY_METER_SOURCE_FS      2U

#define APP_MOTOR_FL                    0U
#define APP_MOTOR_FR                    1U
#define APP_MOTOR_RL                    2U
#define APP_MOTOR_RR                    3U

#define APP_HALL_FAULT_BIT              (1UL << 18)
#define APP_IMD_FAULT_BIT               (1UL << 19)

#endif /* __APP_CONFIG_H__ */
