/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "fsae_telemetry.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(fsae_PacketHeader, fsae_PacketHeader, AUTO)


PB_BIND(fsae_Alarm, fsae_Alarm, AUTO)


PB_BIND(fsae_FastTelemetry, fsae_FastTelemetry, AUTO)


PB_BIND(fsae_IvtTelemetry, fsae_IvtTelemetry, AUTO)


PB_BIND(fsae_EnergyMeterTelemetry, fsae_EnergyMeterTelemetry, AUTO)


PB_BIND(fsae_MotionTelemetry, fsae_MotionTelemetry, AUTO)


PB_BIND(fsae_ThermalRawChunk, fsae_ThermalRawChunk, AUTO)


PB_BIND(fsae_ThermalSensorSummary, fsae_ThermalSensorSummary, AUTO)


PB_BIND(fsae_ThermalSummary, fsae_ThermalSummary, 2)


PB_BIND(fsae_MotorState, fsae_MotorState, AUTO)


PB_BIND(fsae_VehicleState, fsae_VehicleState, AUTO)


PB_BIND(fsae_BatteryModule, fsae_BatteryModule, AUTO)


PB_BIND(fsae_TelemetryFrame, fsae_TelemetryFrame, 2)











